language: node_js
node_js:
  - 16
before_install:
  - cd backend
install:
  - npm install
cache:
  directories:
    - node_modules
env:
  global:
    - NODE_ENV=test
script:
  - npm run
notifications:
  email: ketchupfoods@gmail.com
