language: node_js
node_js:
  - 17
before_install:
  - cd backend
install:
  - npm install
cache:
  directories:
    - node_modules
# before_script: chmod 0777 ./backend/node_modules/.bin/mocha
env:
  global:
    - NODE_ENV=test
script:
  - npm run test
notifications:
  email: ketchupfoods@gmail.com
